<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudentAssistant.Domain\StudentAssistant.Domain.csproj" />
    <ProjectReference Include="..\StudentAssistant.Data\StudentAssistant.Data.csproj" />
    <ProjectReference Include="..\StudentAssistant.Service\StudentAssistant.Service.csproj" />
  </ItemGroup>

</Project>
